### ISSUE TITLE
AUR package checksum fails

### ISSUE THREAD

**Issue by tommyalatalo** [ransome1/sleek#117]
The checksum for the zip file downloaded in the PKGBUILD seems to be incorrect. 
```
==> Making package: sleek 1.0.3-1 (2021-05-05T09:30:54 CEST)
==> Retrieving sources...
  -> Downloading v1.0.3.zip...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   129  100   129    0     0    470      0 --:--:-- --:--:-- --:--:--   470
100 9183k    0 9183k    0     0  6180k      0 --:--:--  0:00:01 --:--:-- 10.7M
  -> Found sleek.desktop
  -> Found sleek.sh
==> Validating source files with sha512sums...
    v1.0.3.zip ... FAILED
    sleek.desktop ... Passed
    sleek.sh ... Passed
==> ERROR: One or more files did not pass the validity check!
error downloading sources: sleek
```

**Comment by ransome1** [comment]
@tommyalatalo , this has been fixed 2 days ago, can you confirm this and close this ticket if so?

**Comment by tommyalatalo** [comment]
No, it doesn't work:
```
❯ yay -S sleek
:: Checking for conflicts...
:: Checking for inner conflicts...
[Repo:2]  nodejs-16.1.0-1  yarn-1.22.10-1
[Aur:1]  sleek-1.0.3-1

  1 sleek                            (Installed) (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==>
:: PKGBUILD up to date, Skipping (1/1): sleek
  1 sleek                            (Installed) (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==>
:: (1/1) Parsing SRCINFO: sleek
resolving dependencies...
looking for conflicting packages...

Packages (2) nodejs-16.1.0-1  yarn-1.22.10-1

Total Download Size:    8,86 MiB
Total Installed Size:  36,09 MiB

:: Proceed with installation? [Y/n]
:: Retrieving packages...
 nodejs-16.1.0-1-x86_64                                                                                          8,9 MiB  10,9 MiB/s 00:01 [------------------------------------------------------------------------------------] 100%
(2/2) checking keys in keyring                                                                                                             [------------------------------------------------------------------------------------] 100%
(2/2) checking package integrity                                                                                                           [------------------------------------------------------------------------------------] 100%
(2/2) loading package files                                                                                                                [------------------------------------------------------------------------------------] 100%
(2/2) checking for file conflicts                                                                                                          [------------------------------------------------------------------------------------] 100%
(2/2) checking available disk space                                                                                                        [------------------------------------------------------------------------------------] 100%
:: Processing package changes...
(1/2) installing nodejs                                                                                                                    [------------------------------------------------------------------------------------] 100%
Optional dependencies for nodejs
    npm: nodejs package manager
(2/2) installing yarn                                                                                                                      [------------------------------------------------------------------------------------] 100%
:: Running post-transaction hooks...
(1/2) Arming ConditionNeedsUpdate...
(2/2) Keep the last cached version and the currently installed.
removed '/home/tommy/.cache/pacman/pkg/nodejs-15.14.0-2-x86_64.pkg.tar.zst'

==> finished: 1 packages removed (disk space saved: 8.58 MiB)
==> Making package: sleek 1.0.3-1 (2021-05-07T19:36:40 CEST)
==> Retrieving sources...
  -> Found v1.0.3.zip
  -> Found sleek.desktop
  -> Found sleek.sh
==> Validating source files with sha512sums...
    v1.0.3.zip ... FAILED
    sleek.desktop ... Passed
    sleek.sh ... Passed
==> ERROR: One or more files did not pass the validity check!
error downloading sources: sleek
```

**Comment by ransome1** [comment]
Can you try again, please?

**Comment by tommyalatalo** [comment]
Still doesn't work, there's a build error:
```
❯ yay -S sleek
:: Checking for conflicts...
:: Checking for inner conflicts...
[Aur:1]  sleek-1.0.3-1

:: Downloaded PKGBUILD (1/1): sleek
  1 sleek                            (Installed) (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==>
:: (1/1) Parsing SRCINFO: sleek
==> Making package: sleek 1.0.3-1 (2021-05-07T22:01:00 CEST)
==> Retrieving sources...
  -> Downloading v1.0.3.zip...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   129    0   129    0     0    443      0 --:--:-- --:--:-- --:--:--   441
100 9291k    0 9291k    0     0  4898k      0 --:--:--  0:00:01 --:--:-- 8320k
  -> Found sleek.desktop
  -> Found sleek.sh
==> Validating source files with sha512sums...
    v1.0.3.zip ... Passed
    sleek.desktop ... Passed
    sleek.sh ... Passed
==> Making package: sleek 1.0.3-1 (2021-05-07T22:01:03 CEST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found v1.0.3.zip
  -> Found sleek.desktop
  -> Found sleek.sh
==> Validating source files with sha512sums...
    v1.0.3.zip ... Passed
    sleek.desktop ... Passed
    sleek.sh ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting v1.0.3.zip with bsdtar
==> Sources are ready.
==> Making package: sleek 1.0.3-1 (2021-05-07T22:01:05 CEST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting build()...
  -> Unzipping v1.0.3.zip
Archive:  v1.0.3.zip
50cd53b0e686e1031da7f5db02e4ceeb2b630a40
  inflating: sleek-1.0.3/.github/ISSUE_TEMPLATE/bug_report.md
  inflating: sleek-1.0.3/.github/ISSUE_TEMPLATE/feature_request.md
  inflating: sleek-1.0.3/.github/workflows/github-ci.yml
  inflating: sleek-1.0.3/.gitignore
  inflating: sleek-1.0.3/LICENSE
  inflating: sleek-1.0.3/PRIVACY.md
  inflating: sleek-1.0.3/README.md
  inflating: sleek-1.0.3/SECURITY.md
 extracting: sleek-1.0.3/assets/icons/128x128.png
 extracting: sleek-1.0.3/assets/icons/22x22.png
 extracting: sleek-1.0.3/assets/icons/24x24.png
 extracting: sleek-1.0.3/assets/icons/256x256.png
 extracting: sleek-1.0.3/assets/icons/32x32.png
 extracting: sleek-1.0.3/assets/icons/48x48.png
  inflating: sleek-1.0.3/assets/icons/512x512.png
 extracting: sleek-1.0.3/assets/icons/64x64.png
 extracting: sleek-1.0.3/assets/icons/96x96.png
  inflating: sleek-1.0.3/assets/icons/icon.png
  inflating: sleek-1.0.3/assets/icons/sleek.icns
  inflating: sleek-1.0.3/assets/icons/sleek.ico
  inflating: sleek-1.0.3/assets/icons/sleek.png
  inflating: sleek-1.0.3/assets/icons/sleek.svg
  inflating: sleek-1.0.3/assets/icons/tray/tray.ico
 extracting: sleek-1.0.3/assets/icons/tray/tray.png
  inflating: sleek-1.0.3/assets/icons/tray/tray.svg
 extracting: sleek-1.0.3/assets/icons/tray/tray@1.25x.png
 extracting: sleek-1.0.3/assets/icons/tray/tray@1.5x.png
 extracting: sleek-1.0.3/assets/icons/tray/tray@1.75x.png
 extracting: sleek-1.0.3/assets/icons/tray/tray@2x.png
 extracting: sleek-1.0.3/assets/icons/tray/tray@3x.png
 extracting: sleek-1.0.3/assets/icons/tray/tray@4x.png
  inflating: sleek-1.0.3/assets/screenshots/linux/category_filtered_dark.png
  inflating: sleek-1.0.3/assets/screenshots/linux/compact_view_dark.png
  inflating: sleek-1.0.3/assets/screenshots/linux/date_picker.png
  inflating: sleek-1.0.3/assets/screenshots/linux/file_switcher.png
  inflating: sleek-1.0.3/assets/screenshots/linux/multiline_autocomplete_dark.png
  inflating: sleek-1.0.3/assets/screenshots/linux/recurrence_picker_dark.png
  inflating: sleek-1.0.3/assets/screenshots/linux/single_context_filtered_dark.png
  inflating: sleek-1.0.3/assets/screenshots/linux/sort_by_due_date_dark.png
  inflating: sleek-1.0.3/assets/screenshots/linux/sort_by_projects.png
  inflating: sleek-1.0.3/assets/screenshots/linux/todo_list.png
  inflating: sleek-1.0.3/assets/screenshots/mac/add_todo.png
  inflating: sleek-1.0.3/assets/screenshots/mac/add_todo_typeahead.png
  inflating: sleek-1.0.3/assets/screenshots/mac/edit_todo.png
  inflating: sleek-1.0.3/assets/screenshots/mac/find_todos.png
  inflating: sleek-1.0.3/assets/screenshots/mac/main.png
  inflating: sleek-1.0.3/assets/screenshots/mac/main_dark.png
  inflating: sleek-1.0.3/assets/screenshots/mac/main_filter_dark.png
  inflating: sleek-1.0.3/assets/screenshots/windows/add_todo.png
  inflating: sleek-1.0.3/assets/screenshots/windows/add_todo_typeahead.png
  inflating: sleek-1.0.3/assets/screenshots/windows/edit_todo.png
  inflating: sleek-1.0.3/assets/screenshots/windows/find_todos.png
  inflating: sleek-1.0.3/assets/screenshots/windows/main.png
  inflating: sleek-1.0.3/assets/screenshots/windows/main_dark.png
  inflating: sleek-1.0.3/assets/screenshots/windows/main_filter_dark.png
  inflating: sleek-1.0.3/assets/sleek.pfx
  inflating: sleek-1.0.3/package.json
 extracting: sleek-1.0.3/snap/gui/icon.png
  inflating: sleek-1.0.3/snap/gui/sleek.desktop
  inflating: sleek-1.0.3/snap/snapcraft.yaml
  inflating: sleek-1.0.3/src/__tests__/jest.js
  inflating: sleek-1.0.3/src/configs/i18next.config.js
  inflating: sleek-1.0.3/src/configs/store.config.js
  inflating: sleek-1.0.3/src/css/dark.css
  inflating: sleek-1.0.3/src/css/datepicker.css
  inflating: sleek-1.0.3/src/css/style.css
 extracting: sleek-1.0.3/src/css/variables.css
  inflating: sleek-1.0.3/src/fonts/FreeSans.otf
  inflating: sleek-1.0.3/src/fonts/FreeSans.ttf
  inflating: sleek-1.0.3/src/fonts/FreeSansBold.otf
  inflating: sleek-1.0.3/src/fonts/FreeSansBold.ttf
  inflating: sleek-1.0.3/src/img/help/add_contexts_projects.png
  inflating: sleek-1.0.3/src/img/help/screenshot_add_due_date.png
  inflating: sleek-1.0.3/src/img/help/screenshot_add_priority.png
  inflating: sleek-1.0.3/src/img/svg/times-circle.svg
  inflating: sleek-1.0.3/src/index.html
  inflating: sleek-1.0.3/src/js/content.mjs
  inflating: sleek-1.0.3/src/js/date.mjs
  inflating: sleek-1.0.3/src/js/datePicker.mjs
  inflating: sleek-1.0.3/src/js/drawer.mjs
  inflating: sleek-1.0.3/src/js/drawer_handle.mjs
  inflating: sleek-1.0.3/src/js/filters.mjs
  inflating: sleek-1.0.3/src/js/form.mjs
  inflating: sleek-1.0.3/src/js/navigation.mjs
  inflating: sleek-1.0.3/src/js/recurrencePicker.mjs
  inflating: sleek-1.0.3/src/js/recurrences.mjs
  inflating: sleek-1.0.3/src/js/todos.mjs
  inflating: sleek-1.0.3/src/js/todotxtExtensions.mjs
  inflating: sleek-1.0.3/src/js/view.mjs
  inflating: sleek-1.0.3/src/locales/de/translation.json
 extracting: sleek-1.0.3/src/locales/de/translation.missing.json
  inflating: sleek-1.0.3/src/locales/en/translation.json
  inflating: sleek-1.0.3/src/locales/en/translation.missing.json
  inflating: sleek-1.0.3/src/locales/es/translation.json
 extracting: sleek-1.0.3/src/locales/es/translation.missing.json
  inflating: sleek-1.0.3/src/locales/fr/translation.json
 extracting: sleek-1.0.3/src/locales/fr/translation.missing.json
  inflating: sleek-1.0.3/src/locales/it/translation.json
 extracting: sleek-1.0.3/src/locales/it/translation.missing.json
  inflating: sleek-1.0.3/src/main.js
  inflating: sleek-1.0.3/src/preload.js
  inflating: sleek-1.0.3/src/render.js
  inflating: sleek-1.0.3/src/scss/dark.scss
  inflating: sleek-1.0.3/src/scss/datepicker.scss
  inflating: sleek-1.0.3/src/scss/style.scss
  inflating: sleek-1.0.3/src/scss/variables.scss
  inflating: sleek-1.0.3/test/mocha.js
  inflating: sleek-1.0.3/yarn.lock
  -> Installing node modules
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
info dmg-license@1.0.8: The platform "linux" is incompatible with this module.
info "dmg-license@1.0.8" is an optional dependency and failed compatibility check. Excluding it from installation.
info iconv-corefoundation@1.1.5: The platform "linux" is incompatible with this module.
info "iconv-corefoundation@1.1.5" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 20.45s.
==> Entering fakeroot environment...
==> Starting package()...
  -> Building sleek with packaged Electron
yarn run v1.22.10
$ electron-builder --dir

/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/errlop/edition-es5/index.js:61
                _this = _super.call(this, input.message || input) || this
                 ^
Error: editions-autoloader-none-broadened: Unable to determine a suitable edition, even after broadening.
    at new Errlop (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/errlop/edition-es5/index.js:61:18)
    at Object.errtion (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/editions/edition-es5/util.js:23:14)
    at determineEdition (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/editions/edition-es5/index.js:317:21)
    at solicitEdition (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/editions/edition-es5/index.js:350:16)
    at Object.requirePackage (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/editions/edition-es5/index.js:364:9)
    at Object.<anonymous> (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/istextorbinary/index.cjs:4:38)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/app-builder-lib/electron-osx-sign/util.js:135:22)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
↳ Error: editions-autoloader-none-suitable: Unable to determine a suitable edition, as none were suitable.
    at new Errlop (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/errlop/edition-es5/index.js:61:18)
    at Object.errtion (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/editions/edition-es5/util.js:23:14)
    at determineEdition (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/editions/edition-es5/index.js:327:19)
    at determineEdition (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/editions/edition-es5/index.js:312:12)
    at solicitEdition (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/editions/edition-es5/index.js:350:16)
    at Object.requirePackage (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/editions/edition-es5/index.js:364:9)
    at Object.<anonymous> (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/istextorbinary/index.cjs:4:38)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/app-builder-lib/electron-osx-sign/util.js:135:22)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
↳ Error: editions-autoloader-edition-incompatible: editions-autoloader-edition-incompatible: The edition [TypeScript source code made to be compatible with Deno] is not compatible with this environment.
    at new Errlop (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/errlop/edition-es5/index.js:61:18)
    at Object.errtion (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/editions/edition-es5/util.js:23:14)
    at determineEdition (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/editions/edition-es5/index.js:301:25)
    at determineEdition (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/editions/edition-es5/index.js:312:12)
    at solicitEdition (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/editions/edition-es5/index.js:350:16)
    at Object.requirePackage (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/editions/edition-es5/index.js:364:9)
    at Object.<anonymous> (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/istextorbinary/index.cjs:4:38)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/app-builder-lib/electron-osx-sign/util.js:135:22)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
↳ Error: editions-autoloader-edition-incompatible: editions-autoloader-edition-incompatible: The edition [TypeScript compiled against ES2019 for Node.js 12 || 14 || 15 with Import for modules] is not compatible with this environment.
    at new Errlop (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/errlop/edition-es5/index.js:61:18)
    at Object.errtion (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/editions/edition-es5/util.js:23:14)
    at determineEdition (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/editions/edition-es5/index.js:301:25)
    at determineEdition (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/editions/edition-es5/index.js:312:12)
    at solicitEdition (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/editions/edition-es5/index.js:350:16)
    at Object.requirePackage (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/editions/edition-es5/index.js:364:9)
    at Object.<anonymous> (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/istextorbinary/index.cjs:4:38)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/app-builder-lib/electron-osx-sign/util.js:135:22)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
↳ Error: editions-autoloader-edition-incompatible: editions-autoloader-edition-incompatible: The edition [TypeScript compiled against ES2019 for Node.js 10 || 12 || 14 || 15 with Require for modules] is not compatible with this environment.
    at new Errlop (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/errlop/edition-es5/index.js:61:18)
    at Object.errtion (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/editions/edition-es5/util.js:23:14)
    at determineEdition (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/editions/edition-es5/index.js:301:25)
    at determineEdition (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/editions/edition-es5/index.js:312:12)
    at solicitEdition (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/editions/edition-es5/index.js:350:16)
    at Object.requirePackage (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/editions/edition-es5/index.js:364:9)
    at Object.<anonymous> (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/istextorbinary/index.cjs:4:38)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/app-builder-lib/electron-osx-sign/util.js:135:22)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
↳ Error: editions-autoloader-edition-incompatible: editions-autoloader-edition-incompatible: The edition [TypeScript compiled against ESNext for Node.js 14 || 15 with Require for modules] is not compatible with this environment.
    at new Errlop (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/errlop/edition-es5/index.js:61:18)
    at Object.errtion (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/editions/edition-es5/util.js:23:14)
    at determineEdition (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/editions/edition-es5/index.js:301:25)
    at determineEdition (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/editions/edition-es5/index.js:312:12)
    at solicitEdition (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/editions/edition-es5/index.js:350:16)
    at Object.requirePackage (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/editions/edition-es5/index.js:364:9)
    at Object.<anonymous> (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/istextorbinary/index.cjs:4:38)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/app-builder-lib/electron-osx-sign/util.js:135:22)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
↳ Error: editions-autoloader-edition-incompatible: editions-autoloader-edition-incompatible: The edition [TypeScript compiled against ES2019 for web browsers with Import for modules] is not compatible with this environment.
    at new Errlop (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/errlop/edition-es5/index.js:61:18)
    at Object.errtion (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/editions/edition-es5/util.js:23:14)
    at determineEdition (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/editions/edition-es5/index.js:301:25)
    at determineEdition (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/editions/edition-es5/index.js:312:12)
    at solicitEdition (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/editions/edition-es5/index.js:350:16)
    at Object.requirePackage (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/editions/edition-es5/index.js:364:9)
    at Object.<anonymous> (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/istextorbinary/index.cjs:4:38)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/app-builder-lib/electron-osx-sign/util.js:135:22)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
↳ Error: editions-autoloader-edition-incompatible: The edition [TypeScript source code with Import for modules] is not compatible with this environment.
    at new Errlop (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/errlop/edition-es5/index.js:61:18)
    at Object.errtion (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/editions/edition-es5/util.js:23:14)
    at isCompatibleEdition (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/editions/edition-es5/index.js:252:19)
    at determineEdition (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/editions/edition-es5/index.js:287:4)
    at determineEdition (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/editions/edition-es5/index.js:312:12)
    at solicitEdition (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/editions/edition-es5/index.js:350:16)
    at Object.requirePackage (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/editions/edition-es5/index.js:364:9)
    at Object.<anonymous> (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/istextorbinary/index.cjs:4:38)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/app-builder-lib/electron-osx-sign/util.js:135:22)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
↳ Error: editions-autoloader-invalid-engines: The edition had no engines to compare against the environment
    at new Errlop (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/errlop/edition-es5/index.js:61:18)
    at Object.errtion (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/editions/edition-es5/util.js:23:14)
    at isCompatibleEngines (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/editions/edition-es5/index.js:183:19)
    at isCompatibleEdition (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/editions/edition-es5/index.js:250:10)
    at determineEdition (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/editions/edition-es5/index.js:287:4)
    at determineEdition (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/editions/edition-es5/index.js:312:12)
    at solicitEdition (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/editions/edition-es5/index.js:350:16)
    at Object.requirePackage (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/editions/edition-es5/index.js:364:9)
    at Object.<anonymous> (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/istextorbinary/index.cjs:4:38)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/home/tommy/.cache/yay/sleek/src/sleek-1.0.3/node_modules/app-builder-lib/electron-osx-sign/util.js:135:22)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
==> ERROR: A failure occurred in package().
    Aborting...
error making: sleek
```

**Comment by ransome1** [comment]
Checksum problem has been solved, further discussion should happen here: https://github.com/ransome1/sleek/issues/109
