### ISSUE TITLE
Unable to start application due to file number watchers limit

### ISSUE THREAD

**Issue by anlar** [ransome1/sleek#265]
**Is it an actual bug?**

Yes.

**Did you check if the bug has already been reported?**

Yes.

**Describe the bug**

When I'm trying to start sleek it shows blank screen with `System limit for number of file watchers reached` error in logs:

```
$ flatpak run com.github.ransome1.sleek
[2 zypak-helper] Error retrieving supports property: org.freedesktop.DBus.Error.InvalidArgs: No such property 'supports'
[2 zypak-helper] Portal v4 is not available
Gtk-Message: 14:46:23.680: Failed to load module "appmenu-gtk-module"
User preferences located at: /home/user/.var/app/com.github.ransome1.sleek/config/sleek/user-preferences.json
libva error: /usr/lib/x86_64-linux-gnu/dri/intel-vaapi-driver/iHD_drv_video.so init failed
Success: Translation loaded for: en
Success: Window events setup
Success: Filewatcher is watching: /mnt/data/share/notes/todo/todo.txt
(node:2) UnhandledPromiseRejectionWarning: Error: ENOSPC: System limit for number of file watchers reached, watch '/mnt/data/notes/todo/todo.txt'
    at FSWatcher.<computed> (internal/fs/watchers.js:218:26)
    at Object.watch (fs.js:1525:34)
    at createFsWatchInstance (/app/sleek/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:119:15)
    at setFsWatchListener (/app/sleek/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:166:15)
    at NodeFsHandler._watchWithNodeFs (/app/sleek/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:331:14)
    at NodeFsHandler._handleFile (/app/sleek/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:395:23)
    at NodeFsHandler._addToNodeFs (/app/sleek/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:629:21)
    at async /app/sleek/resources/app.asar/node_modules/chokidar/index.js:451:21
    at async Promise.all (index 0)
(Use `sleek --trace-warnings ...` to show where the warning was created)
(node:2) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Failed to open '/app/sleek/resources/app.asar/src/index.html': Not a directoryFailed to open '/app/sleek/resources/app.asar/src/index.html': Not a directoryFailed to open '/app/sleek/resources/app.asar/src/index.html': Not a directoryFailed to open '/app/sleek/resources/app.asar/src/index.html': Not a directoryFailed to open '/app/sleek/resources/app.asar/src/index.html': Not a directory[10 zypak-sandbox] Dropping 0x1243250 (3) because of connection closed
[10 zypak-sandbox] Host is gone, preparing to exit...
[10 zypak-sandbox] Quitting Zygote...
```

But it seems that I have enough  available watchers:

```
$ lsof | grep inotify | wc -l
58
$ sysctl fs.inotify
fs.inotify.max_queued_events = 16384
fs.inotify.max_user_instances = 1024
fs.inotify.max_user_watches = 8192
```

**To Reproduce**
1. Launch application.
2. See blank screen

**Do you see any error entries in sleeks developer tools?**

No.

**Expected behavior**

Application should display todo.txt.

**Screenshots**

No.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Version of sleek: 1.1.1
 - Source: Flathub

**Comment by ransome1** [comment]
@anlar : I improved the filewatcher setup and managed to get rid of this issue on my side. Can I ask you to give this pre release a try and let me know if this fixes anything on your side as well? https://github.com/ransome1/sleek/releases/tag/v1.1.2-rc.3

**Comment by anlar** [comment]
@ransome1 Thanks for the update.

I have updated to v1.1.2 from Flathub and right now I'm not able to reproduce that error.
