### ISSUE TITLE
sleek can no longer read my todo.txt -- Error: EMFILE: too many open files

### ISSUE THREAD

**Issue by gdevenyi** [ransome1/sleek#302]
**Describe the bug**
Sleek can no longer open my todo.txt, complains about this:
```
User preferences located at: /home/gdevenyi/.config/sleek/user-preferences.json
Success: Translation loaded for: en
Success: Window events setup
Success: Filewatcher is watching: /home/gdevenyi/Sync/todo.txt
(node:1978) UnhandledPromiseRejectionWarning: Error: EMFILE: too many open files, watch '/home/gdevenyi/Sync/todo.txt'
    at FSWatcher.<computed> (internal/fs/watchers.js:218:26)
    at Object.watch (fs.js:1525:34)
    at createFsWatchInstance (/opt/sleek/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:119:15)
    at setFsWatchListener (/opt/sleek/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:166:15)
    at NodeFsHandler._watchWithNodeFs (/opt/sleek/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:331:14)
    at NodeFsHandler._handleFile (/opt/sleek/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:395:23)
    at NodeFsHandler._addToNodeFs (/opt/sleek/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:629:21)
    at async /opt/sleek/resources/app.asar/node_modules/chokidar/index.js:451:21
    at async Promise.all (index 0)
    at emitUnhandledRejectionWarning (internal/process/promises.js:168:15)
    at processPromiseRejections (internal/process/promises.js:247:11)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
(node:1978) Error: EMFILE: too many open files, watch '/home/gdevenyi/Sync/todo.txt'
    at FSWatcher.<computed> (internal/fs/watchers.js:218:26)
    at Object.watch (fs.js:1525:34)
    at createFsWatchInstance (/opt/sleek/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:119:15)
    at setFsWatchListener (/opt/sleek/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:166:15)
    at NodeFsHandler._watchWithNodeFs (/opt/sleek/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:331:14)
    at NodeFsHandler._handleFile (/opt/sleek/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:395:23)
    at NodeFsHandler._addToNodeFs (/opt/sleek/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:629:21)
    at async /opt/sleek/resources/app.asar/node_modules/chokidar/index.js:451:21
    at async Promise.all (index 0)
(node:1978) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitDeprecationWarning (internal/process/promises.js:180:11)
    at processPromiseRejections (internal/process/promises.js:249:13)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
```

**To Reproduce**
Unclear, this may be something which has changed about my system. 

**Do you see any error entries in sleeks developer tools?**
![image](https://user-images.githubusercontent.com/3001850/144919610-225d28fe-b4cf-4d24-8e5f-621a379623a4.png)

**Expected behavior**
It works

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Version of sleek 1.1.4rc4
 - Source: Deb from github

**Comment by gdevenyi** [comment]
Google points me here for nodejs too many open files https://stackoverflow.com/questions/8965606/node-and-error-emfile-too-many-open-files

**Comment by gdevenyi** [comment]
After a reboot this has gone away. I guess something in the system was holding open too many file watches?

**Comment by ransome1** [comment]
Let's leave this one open. I was already looking into it a bit, but couldn't find any good reason why sleek would open and not close existing file watchers. But I want to dig a bit deeper.

If you somehow can reproduce it further down the way, please let me know how you did that.

I'll report back here, once I find something.

**Comment by gdevenyi** [comment]
> If you somehow can reproduce it further down the way, please let me know how you did that.

Will do, its not clear to me right now if it was watchers from sleek or watchers from other software on the system causing the issue.

**Comment by ransome1** [comment]
Do you have any file syncing app (Dropbox, Syncthing) or any other todo.txt app running?

**Comment by gdevenyi** [comment]
I have Syncthing monitoring its default share directory, which has two files, `todo.txt` and `todo_done.txt`

**Comment by ransome1** [comment]
I have the same setup with Syncthing here. Never had a problem with it, but you never know.

**Comment by ransome1** [comment]
This morning I was able to provoke this one
`(node:89599) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 userData listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit`

I'm not sure how or if it is connected, but it happened after I had sleek running and putting the computer into stand by and waking it up again for several times. Maybe waking the computer up generates new listeners and old ones are not being killed. But no matter what it is, I'm on it ;)

Anyhow, is the standby/wake up scenario maybe something that came into play in your setup as well?

**Comment by gdevenyi** [comment]
I just upgraded from 1.1.4rc4 to 1.1.5. Sleek was closed before upgrade, upon opening again:
```
$ sleek
User preferences located at: /home/gdevenyi/.config/sleek/user-preferences.json
Success: Translation loaded for: en
Success: Window events setup
Success: Filewatcher is watching: /home/gdevenyi/Sync/todo.txt
(node:4604) UnhandledPromiseRejectionWarning: Error: EMFILE: too many open files, watch '/home/gdevenyi/Sync/todo.txt'
    at FSWatcher.<computed> (internal/fs/watchers.js:218:26)
    at Object.watch (fs.js:1525:34)
    at createFsWatchInstance (/opt/sleek/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:119:15)
    at setFsWatchListener (/opt/sleek/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:166:15)
    at NodeFsHandler._watchWithNodeFs (/opt/sleek/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:331:14)
    at NodeFsHandler._handleFile (/opt/sleek/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:395:23)
    at NodeFsHandler._addToNodeFs (/opt/sleek/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:629:21)
    at async /opt/sleek/resources/app.asar/node_modules/chokidar/index.js:451:21
    at async Promise.all (index 0)
    at emitUnhandledRejectionWarning (internal/process/promises.js:168:15)
    at processPromiseRejections (internal/process/promises.js:247:11)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
(node:4604) Error: EMFILE: too many open files, watch '/home/gdevenyi/Sync/todo.txt'
    at FSWatcher.<computed> (internal/fs/watchers.js:218:26)
    at Object.watch (fs.js:1525:34)
    at createFsWatchInstance (/opt/sleek/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:119:15)
    at setFsWatchListener (/opt/sleek/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:166:15)
    at NodeFsHandler._watchWithNodeFs (/opt/sleek/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:331:14)
    at NodeFsHandler._handleFile (/opt/sleek/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:395:23)
    at NodeFsHandler._addToNodeFs (/opt/sleek/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:629:21)
    at async /opt/sleek/resources/app.asar/node_modules/chokidar/index.js:451:21
    at async Promise.all (index 0)
(node:4604) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitDeprecationWarning (internal/process/promises.js:180:11)
    at processPromiseRejections (internal/process/promises.js:249:13)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)

```

**Comment by gdevenyi** [comment]
Using the info from this: https://stackoverflow.com/a/60705427 I'm nowhere near my limits for watches on the system.

**Comment by gdevenyi** [comment]
Another update,
I had
`fs.inotify.max_user_instances = 128`

which I changed to:
`fs.inotify.max_user_instances = 256`

And again sleek is working.

Doing some sleuthing, something (sleek or otherwise) is using too many instances to do its notification, instead of adding watches within a single instance.
https://unix.stackexchange.com/questions/532709/what-is-exactly-difference-between-inotify-max-user-instances-and-max-user-watch

**Comment by gdevenyi** [comment]
Looks like KDE, followed by ferdi is at fault here,
```
# for foo in /proc/*/fd/*; do readlink -f $foo; done | grep inotify | sort | uniq -c | sort -nr
     48 /proc/4939/fd/anon_inode:inotify
     13 /proc/5017/fd/anon_inode:inotify
      8 /proc/4889/fd/anon_inode:inotify
```

```
# ps aux | grep 4939
gdevenyi  4939  0.5  0.8 9969172 1144792 ?     Sl   Dec13  70:41 /usr/bin/plasmashell
# ps aux | grep 5017
gdevenyi  5017  0.8  0.2 21799504 270712 ?     Sl   Dec13 113:52 /opt/Ferdi/ferdi
# ps aux | grep 4889
gdevenyi  4889  0.0  0.0 3741404 67388 ?       Sl   Dec13   3:55 /usr/bin/kded5
```

I'm just on the edge of 128 instances which is causing the issue. Not a sleek bug, KDE bug.

**Comment by ransome1** [comment]
@gdevenyi that's kind of a relieve as I couldn't come up with any solution to this. I wasn't even able to reproduce it. Thanks for looking into it.
