### ISSUE TITLE
Tray icon fails to load

### ISSUE THREAD

**Issue by jkdel** [ransome1/sleek#580]
## Bug Report

**App Version:** 2.0.2

**Platform:** Linux

**Installation Method:** AUR

**Bug Description:**
Fallback icon in systray. Clicking the icon does not open Sleek when the app is reduced to systray.

**Steps to Reproduce:**
1. Open Sleek → fallback icon in systray
2. Activate setting "minimize to taskbar"
3. Close the window
4. Clicking the systray icon does nothing

**Expected Behavior:**
- Expected Sleek icon in systray
- Expected clicking the systray icon to open Sleek

**Additional Information:** Console log

    main.ts: Error: Failed to load image from path '/usr/lib/sleek/app.asar/assets/icons/tray/tray.png'
        at de (/usr/lib/sleek/app.asar/dist/main/main.js:8:260030)
        at /usr/lib/sleek/app.asar/dist/main/main.js:8:270632

The correct path on my system would be  '/usr/lib/sleek/assets/icons/tray/tray.png'

**Comment by ransome1** [comment]
> The correct path on my system would be '/usr/lib/sleek/assets/icons/tray/tray.png'

After installing sleek through AUR, that particular png is located in exactly this location? It would really surprise me, because I think this means sleek had not been packaged during the installation process. Can you check with your terminal or file browser if you can reach that file like this? 

Can you check real quick if this also happens if you use the [AppImage](https://github.com/ransome1/sleek/releases/download/v2.0.3-rc.2/sleek-2.0.3-rc.2.AppImage) release? I need to make sure, this only happens with AUR only. 

Also, how did you install sleek? With `yay`?

**Comment by jkdel** [comment]
Hi,

thanks for the nice app and looking into the issue. I should have provided these details in the first place I guess (hadn't tested the AppImage though):

- After installing sleek-bin (2.0.2-1) via yay I get the error `main.ts: Error: Failed to load image from path '/usr/lib/sleek/app.asar/assets/icons/tray/tray.png'` and can find the file at /usr/lib/sleek/assets/icons/tray/tray.png
- After installing sleek (2.0.1-1) via yay I get the error `main.ts: Error: Failed to load image from path '/usr/lib/sleek.asar/assets/icons/tray/tray.png'`. I can find the asar archive at the name location but still only have a placeholder icon in the tray and after unpacking the asar archive, there was no icon to be found.
- With the AppImage (2.0.3-rc2) there is no issue (`main.ts: Tray created` and clicking the tray icon opens the window)

The AUR packages are the currently available versions there. I've just noticed that the AppImage is more up to date.

The issue occurs on Arch Linux with Gnome and the [AppIndicator and KStatusNotifierItem Support](https://extensions.gnome.org/extension/615/appindicator-support/) shell extension. However, since it works with the AppImage and the path error messages are explicit, this is unlikely to be the issue I guess.

**Comment by ransome1** [comment]
I think it has something to do with the way the releases in AUR are being built. Thus this bug report is fully valid.

**Comment by warmwaffles** [comment]
I can try a rebuild of the package

**Comment by warmwaffles** [comment]
I updated the AUR to v2.0.2 from v2.0.1

**Comment by ransome1** [comment]
I havn't yet found the time to look into it. Somehow we need to include the missing icons into the .asar file during the build process. I won't be able to fix this before 2.0.4 I'm afraid. But it's in the backlog.

**Comment by ransome1** [comment]
@warmwaffles @jkdel the way the icons in sleeks are handled has changed. Can you please check if 2.0.15 on aur solves the issue?

**Comment by warmwaffles** [comment]
Running on my machine I was able to catch this:

```
$ sleek

config.ts: sleek userdata is located at: /home/warmwaffles/.config/sleek/userData
Watching new file: /home/warmwaffles/todo/vicai/todo.txt
[37126:0116/082841.602124:ERROR:browser_main_loop.cc(278)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
Styles injected found in CSS file: /home/warmwaffles/.config/sleek/userData/customStyles.css
Set drawerWidth to 500

### I closed sleek here to minimize to tray ###

### Clicked tray icon to reopen ###

Destroyed old file watcher
Watching new file: /home/warmwaffles/todo/vicai/todo.txt
[37126:0116/082845.666072:ERROR:browser_main_loop.cc(278)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
Styles injected found in CSS file: /home/warmwaffles/.config/sleek/userData/customStyles.css
fish: Job 1, 'sleek' terminated by signal SIGSEGV (Address boundary error)
```

I should note, I am using `bspwm` and `polybar` which has a tray module.

**Comment by ransome1** [comment]
Did the application crash?

**Comment by warmwaffles** [comment]
hahah yes, with a `SIGSEGV`, so something is up with GTK.

```
'sleek' terminated by signal SIGSEGV (Address boundary error)
```

**Comment by ransome1** [comment]
Unfortunately I am on an older silicon Macbook nowadays and getting Linux to run in UTM is extremely time consuming. I'm glad my Ubuntu VM is up and running. @jkdel @LekkerKofi @tommyalatalo @callegar maybe you could provide us with some feedback here.

**Comment by ransome1** [comment]
> > Can you please check if 2.0.15 on aur solves the issue?
> 
> Yes, it does. When I click on the tray icon, the windows opens. However, when I click the tray icon while the window is open, it doesn't close. Is this intended behavior?

The behavior of the tray has been a long ongoing discussion. And a very painful one. It kind of is complicated because users of the different OS all seems to have different expectations on how it should work. And since this is an Electron app, it is not the easiest task to find this behavior that fits every expectation.

Currently we have it implemented in the most default way Electron advises it to be implemented. 

In the past however we tried to customize it for the different OS. And it was a mess. For example we got user reports, which indicated that every desktop environment on Linux showed a different behavior of the tray, not documented in the Electron documentation.

Before we touch this hot steel again, I think we should open up a discussion and precisely define the expected behavior on all different OS and windows managers.

**Comment by ransome1** [comment]
And regarding this topic: At least the icon is now present in AUR builds, so that's good news. Thanks for reporting back @LekkerKofi

**Comment by ransome1** [comment]
@LekkerKofi @warmwaffles does the tray icon is shown in high resolution or looks rather pixelated on your end?

**Comment by ransome1** [comment]
Main issue (tray icon fails to load) is solved in 2.0.16. As for the click behavior, I opened a discussion to gather requirements.
